### ISSUE TITLE
Section 2.9 watching actors suggestion

### ISSUE THREAD

**Issue by Heysem** [rockthejvm/akka-essentials#1]
Small nitpick but do you really need to use active(children - childName) here since removing the child from the map is already taken care of on line 121. Instead you can use Behaviours.Same
https://github.com/rockthejvm/akka-essentials/blob/372e525a5c7f8c361938c319e8de117797c7cc85/src/main/scala/part2actors/ChildActors.scala#L133

**Comment by daniel-ciocirlan** [comment]
You do need that in the case that the child gets killed for some other
reason.
